### ISSUE TITLE
Error: Unsupported arguments for aws_kinesis_firehose_delivery_stream resource

### ISSUE THREAD

**Issue by coolbrewed** [spacelift-io-examples/terraform-aws-spacelift-events-collector#4]
# Issue
When referencing the collector module with the latest version of the AWS Provider (~5.20.x), the module runs into two errors:
> Error: Unsupported argument
>
> on .terraform/modules/audit_trail_collector/main.tf line 107, in resource "aws_kinesis_firehose_delivery_stream" "stream":
> 107:     buffer_interval     = var.buffer_interval
>
> An argument named "buffer_interval" is not expected here.

And:

> Error: Unsupported argument
>
> on .terraform/modules/audit_trail_collector/main.tf line 108, in resource "aws_kinesis_firehose_delivery_stream" "stream":
> 108:     buffer_size     = var.buffer_size
>
> An argument named "buffer_size" is not expected here.

Looks like the AWS Provider did a bit of renaming in the latest releases.
So for the [`aws_kinesis_firehose_delivery_stream` Resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#argument-reference), the argument name changes now seem to be:
- `buffer_size` -> `buffering_size`
- `buffer_interval` -> `buffering_interval`

https://github.com/spacelift-io-examples/terraform-aws-spacelift-events-collector/blob/cd4e72e1580bedc72c96f68997b6840755ac8184/main.tf#L107-L108

**Comment by beforster** [comment]
@jmfontaine I opened the above PR with changes in the event that your team is comfortable with this version upgrade.

**Comment by TheOutdoorProgrammer** [comment]
Fixed via https://github.com/spacelift-io-examples/terraform-aws-spacelift-events-collector/pull/6
